// <auto-generated />
using DatabasePrincess.Data.AttemptsRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabasePrincess.Migrations
{
    [DbContext(typeof(AttemptsContext))]
    partial class AttemptsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DatabasePrincess.Data.AttemptsRepo.Model.AttemptDto", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("AttemptId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("DatabasePrincess.Data.AttemptsRepo.Model.ContenderDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptDtoAttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttemptDtoAttemptId");

                    b.ToTable("ContenderDto");
                });

            modelBuilder.Entity("DatabasePrincess.Data.AttemptsRepo.Model.ContenderDto", b =>
                {
                    b.HasOne("DatabasePrincess.Data.AttemptsRepo.Model.AttemptDto", "AttemptDto")
                        .WithMany("Contenders")
                        .HasForeignKey("AttemptDtoAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttemptDto");
                });

            modelBuilder.Entity("DatabasePrincess.Data.AttemptsRepo.Model.AttemptDto", b =>
                {
                    b.Navigation("Contenders");
                });
#pragma warning restore 612, 618
        }
    }
}
